name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: arunsidnal/myrepository
        tags: v1, latest
        registry: docker.io
        dockerfile: ./APIContainerService/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Docker Pull and Run from Image
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.AWSHOST }}
       username: ${{ secrets.AWSUSERNAME }}
       key: ${{ secrets.AWSKEY }}
       port: ${{ secrets.PORT }}
       script: |
              sudo systemctl start docker
              sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
              sudo docker pull ${{secrets.DOCKER_USER}}:latest
              sudo docker stop weatherserviceapi
              sudo docker rm weatherserviceapi
              sudo docker run -d --name weatherserviceapi -p 80:8080 ${{secrets.DOCKER_USER}}:latest
              
              
        
        
        
     
     
